extends SceneTree

const AudioManagerScript = preload("res://scripts/core/AudioManager.gd")

func _init() -> void:
	call_deferred("_run")

func _run() -> void:
	var audio = AudioManagerScript.new()
	root.add_child(audio)
	await process_frame
	_check(audio.event_profiles.has("card_attack"), "audio manager has attack card event")
	_check(audio.event_profiles.has("card_skill"), "audio manager has skill card event")
	_check(audio.event_profiles.has("card_power"), "audio manager has power card event")
	_check(audio.event_stream_paths.size() >= audio.event_profiles.size(), "audio manager maps configured events to stream paths")
	_check(audio.stream_asset_count() == audio.event_stream_paths.size(), "audio manager has generated wav assets for every stream event")
	_check(audio.stream_asset_exists("card_attack"), "audio manager can find generated attack wav")
	_check(audio.stream_asset_exists("phase"), "audio manager can find generated phase wav")
	_check(audio.stream_asset_exists("phase_forge"), "audio manager maps forge phase audio")
	_check(audio.stream_asset_exists("phase_storm"), "audio manager maps storm phase audio")
	_check(audio.stream_asset_exists("phase_nexus"), "audio manager maps nexus phase audio")
	_check(audio.music_stream_paths.size() >= 10, "audio manager maps core music contexts to stream paths")
	_check(audio.music_asset_count() == audio.music_stream_paths.size(), "audio manager has generated wav assets for every music context")
	_check(audio.music_asset_exists("combat"), "audio manager can find generated combat music loop")
	_check(audio.music_asset_exists("boss"), "audio manager can find generated boss music loop")
	audio.apply_settings({"audio_enabled": false, "master_volume": 1.5, "music_enabled": false, "music_volume": 1.4})
	_check(not audio.enabled, "audio manager applies enabled setting")
	_check(is_equal_approx(audio.master_volume, 1.0), "audio manager clamps high master volume")
	_check(not audio.music_enabled, "audio manager applies music enabled setting")
	_check(is_equal_approx(audio.music_volume, 1.0), "audio manager clamps high music volume")
	audio.apply_settings({"audio_enabled": true, "master_volume": -0.2, "music_enabled": true, "music_volume": -0.4})
	_check(audio.enabled and is_equal_approx(audio.master_volume, 0.0), "audio manager clamps low master volume")
	_check(audio.music_enabled and is_equal_approx(audio.music_volume, 0.0), "audio manager clamps low music volume")
	audio.apply_settings({"audio_enabled": true, "master_volume": 0.7, "music_enabled": true, "music_volume": 0.5})
	_check(is_equal_approx(audio.master_volume, 0.7), "audio manager applies master volume")
	_check(is_equal_approx(audio.music_volume, 0.5), "audio manager applies music volume")
	audio.play_event("ui_click")
	_check(audio.last_event_id == "ui_click" and audio.last_stream_loaded and audio.last_playback_mode == "stream", "ui click uses generated stream asset")
	audio.play_event("card_play")
	audio.play_event("card_attack")
	_check(audio.last_stream_path.ends_with("card_attack.wav") and audio.last_stream_loaded, "attack card uses generated attack wav")
	audio.play_event("card_skill")
	audio.play_event("card_power")
	audio.play_event("hit")
	audio.play_event("block")
	audio.play_event("heal")
	audio.play_event("phase")
	audio.play_event("victory")
	audio.play_event("defeat")
	audio.play_event("missing_event")
	_check(audio.last_event_id == "missing_event" and audio.last_stream_path.ends_with("ui_click.wav") and audio.last_stream_loaded, "missing audio events fall back to default stream")
	audio.play_music_context("combat")
	_check(audio.last_music_context == "combat" and audio.last_music_stream_loaded and audio.last_music_stream_path.ends_with("combat_loop.wav"), "combat music context uses generated loop")
	audio.play_music_context("boss")
	_check(audio.last_music_context == "boss" and audio.last_music_stream_loaded and audio.last_music_stream_path.ends_with("boss_loop.wav"), "boss music context uses generated loop")
	audio.play_music_context("missing_context")
	_check(audio.last_music_context == "missing_context" and audio.last_music_stream_loaded and audio.last_music_stream_path.ends_with("menu_loop.wav"), "missing music contexts fall back to menu loop")
	root.remove_child(audio)
	audio.queue_free()
	await process_frame
	print("Audio manager smoke test passed.")
	quit(0)

func _check(condition: bool, message: String) -> void:
	if not condition:
		push_error("Test failed: %s" % message)
		quit(1)
